<?php 
return array(
	'View/hy_moblie2018/thread_list.html'=>array(
		'vmlb1'=>'vmlb2',
	),
	'View/hy_moblie2018/thread_index.html'=>array(
		'vmtz1'=>'vmtz2',
	),
	'View/hy_moblie2018/thread_header.html'=>array(
		'vmtzh1'=>'vmtzh2',
	),
	'View/tlmsu/thread_list.html'=>array(
		'vmlb1'=>'vmlb2',
	),
	'View/tlmsu/thread_index.html'=>array(
		'vmtz1'=>'vmtz2',
	),
	'View/tlmsu/thread_header.html'=>array(
		'vmtzh1'=>'vmtzh2',
	),
	'View/hybbs/thread_list.php'=>array(
		'vlb1'=>'vlb2',
	),
	'View/hybbs/thread_index.php'=>array(
		'vtz1'=>'vtz2',
		'vtz3'=>'vtz4',
	),
);